api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('ingredients/', views.check_ingredient, name='check_ingredient'),
    path('subscriptions/', views.add_subscription, name='add_subscription'),
    path('subscriptions/<int:author_id>/',
         views.remove_subscription, name='remove_subscription'),
    path('favorites/', views.add_favorites, name='add_favorites'),
    path('favorites/<int:recipe_id>/',
         views.remove_favorites, name='remove_favorites'),
    path('purchases/', views.add_purchases, name='add_purchases'),
    path('purchases/<int:recipe_id>/',
         views.remove_purchases, name='remove_purchases'),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.flatpages import views
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('django.contrib.flatpages.urls')),
]


urlpatterns += [
    path('about/about-author/', views.flatpage,
         {'url': '/about-author/'}, name='about-author'),
    path('about/about-spec/', views.flatpage,
         {'url': '/about-spec/'}, name='about-spec'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


handler404 = 'foodgram.views.page_not_found' # noqa
handler500 = 'foodgram.views.server_error' # noqa

recipes/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_recipe, name='create'),
    path('subscription/', views.subscriptions, name='subscriptions'),
    path('favorite/', views.favorite, name='favorites'),
    path('purchase/', views.purchase, name='purchases'),
    path('purchase/download/', views.get_purchase, name='get_purchase'),
    path('purchase/<int:recipe_id>/',
         views.remove_purchase, name='remove_purchase'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:recipe_id>/',
         views.single_recipe, name='recipe'),
    path('<str:username>/<int:recipe_id>/edit/',
         views.edit_recipe, name='edit_recipe'),
    path('<str:username>/<int:recipe_id>/remove/',
         views.remove_recipe, name='remove_recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Tag(models.Model):
    """Теги"""
    key = models.CharField(max_length=128, unique=True, verbose_name='Ключ')
    value = models.CharField(max_length=128, verbose_name='Значение')


class Recipe(models.Model):
    """Рецепты"""
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes', verbose_name='Автор')
    title = models.CharField(max_length=256, verbose_name='Наименование')
    image = models.ImageField(upload_to='recipes/',
                              blank=True,
                              null=True,
                              verbose_name='Изображение')
    description = models.TextField(blank=True,
                                   null=True,
                                   verbose_name='Описание')
    ingredients = models.ManyToManyField('Ingredient',
                                         through='Amount',
                                         through_fields=('recipe',
                                                         'ingredient'),
                                         verbose_name='Ингредиенты')
    tags = models.ManyToManyField(Tag, verbose_name='Тег')
    time = models.PositiveIntegerField(verbose_name='Время приготовления')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    db_index=True,
                                    verbose_name="Дата публикации")
    
    class Meta:
        ordering = ('-pub_date', )
        
    def __str__(self):
        return self.title


class Ingredient(models.Model):
    """Ингредиенты"""
    title = models.CharField(max_length=128,
                             unique=True, verbose_name='Наименование')
    dimension = models.CharField(max_length=128,
                                 verbose_name='Мера')
    
    def __str__(self):
        return f"{self.title} ({self.dimension})"
    

class Amount(models.Model):
    """Колличество ингредиетов в рецепте"""
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE,
                                   verbose_name='Ингредиент')
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               verbose_name='Рецепт')
    quantity = models.PositiveIntegerField(verbose_name='Колличество')


class Favorite(models.Model):
    """Рецепты избранные"""
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='favorites',
                             verbose_name='Пользователь')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='favorites',
                               verbose_name='Понравившейся рецепт')
    
    
class Purchase(models.Model):
    """Рецетов на покупки"""
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='purchases',
                             verbose_name='Пользователь')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='purchases',
                               verbose_name='Рецепт')

recipes/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField


from .models import Recipe, Tag


class RecipeForm(ModelForm):
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                    to_field_name='key')

    class Meta:
        model = Recipe
        fields = ['title', 'time', 'description', 'image']

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum

from .models import Recipe, Amount, User, Tag, Purchase
from .forms import RecipeForm
from .business_functions import (get_file_content,
                                 get_dict_ingredient,
                                 get_filters_recipes)


def index(request):
    filters, recipes = get_filters_recipes(request)

    tags = Tag.objects.all()

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    content = {'page': page,
               'paginator': paginator,
               'tags': tags,
               'filter': filters,
               }

    return render(request, 'index.html', content)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    filters, recipes = get_filters_recipes(request, author=author.id)

    tags = Tag.objects.all()

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    content = {'page': page,
               'paginator': paginator,
               'tags': tags,
               'filter': filters,
               'author': author,
               }

    return render(request, 'index.html', content)


@login_required
def favorite(request):
    user = request.user
    filters, recipes = get_filters_recipes(request, favorites__user=user)

    tags = Tag.objects.all()

    paginator = Paginator(recipes, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    content = {'page': page,
               'paginator': paginator,
               'tags': tags,
               'filter': filters,
               'favorite': True,
               }

    return render(request, 'index.html', content)


@login_required
def purchase(request):
    user = request.user
    purchases = Purchase.objects.filter(user=user).prefetch_related('recipe')

    content = {'purchases': purchases, }

    return render(request, 'recipes/purchase.html', content)


@login_required
def remove_purchase(request, recipe_id):
    user = request.user
    purchase = get_object_or_404(Purchase, recipe=recipe_id, user=user.id)
    purchase.delete()

    return redirect('purchases')


def single_recipe(request, username, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, author__username=username)
    ingredients = Amount.objects.filter(recipe=recipe_id)

    content = {'recipe': recipe,
               'ingredients': ingredients,
               }

    return render(request, 'recipes/recipe_page.html', content)


@login_required
def create_recipe(request):
    form = RecipeForm(request.POST or None, files=request.FILES or None)

    if form.is_valid():
        ingredients = get_dict_ingredient(request.POST)
        recipe = form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        recipe.tags.set(form.cleaned_data['tags'])

        for ingredient, value in ingredients.items():
            Amount.objects.create(ingredient=ingredient,
                                  recipe=recipe,
                                  quantity=value)

        return redirect('index')

    context = {'form': form}

    return render(request, 'recipes/form_recipe.html', context)


@login_required
def edit_recipe(request, username, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id, author__username=username)

    if recipe.author != request.user:
        return redirect('recipe', username=username, recipe_id=recipe_id)

    form = RecipeForm(
        request.POST or None, files=request.FILES or None, instance=recipe)

    if form.is_valid():
        ingredients = get_dict_ingredient(request.POST)
        recipe = form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        recipe.tags.set(form.cleaned_data['tags'])
        Amount.objects.filter(recipe_id=recipe.id).delete()
        for ingredient, value in ingredients.items():
            Amount.objects.create(ingredient=ingredient,
                                  recipe=recipe,
                                  quantity=value)

        return redirect('recipe', username=username, recipe_id=recipe_id)

    ingredients = Amount.objects.filter(recipe=recipe_id)

    active_tags = list(recipe.tags.values_list('key', flat=True))

    context = {'form': form,
               'recipe': recipe,
               'ingredients': ingredients,
               'active_tags': active_tags
               }
    return render(request, 'recipes/form_recipe.html', context)


@login_required
def remove_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


@login_required
def subscriptions(request):
    user = request.user
    authors = User.objects.filter(
        following__user=user).prefetch_related('recipes').order_by('-username')
    paginator = Paginator(authors, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {'page': page, 'paginator': paginator, }

    return render(request, 'recipes/subscription.html', context)


@login_required
def get_purchase(request):
    user = request.user

    purchases_id = Purchase.objects.filter(user=user).values_list('recipe')
    ingredients = Amount.objects.filter(
        recipe__in=purchases_id).prefetch_related('ingredient').values(
        'ingredient__title', 'ingredient__dimension').annotate(Sum('quantity'))

    filename, file_content = get_file_content(ingredients, user)

    response = HttpResponse(file_content,
                            content_type='application/text charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename={filename}'

    return response

recipes/templates/recipes/form_recipe.html
{% extends "base.html" %}

{% block title %}
    {% if recipe %}
        Редактирование рецепта
    {% else %}
        Создание рецепта
    {% endif %}
{% endblock %}

{% load user_filters %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}


{% block content %}
    <div class="main__header">
        <h1 class="main__title">
            {% if recipe %}
                Редактирование рецепта
            {% else %}
                Создание рецепта
            {% endif %}
        </h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="breakfast" id="id_breakfast"
                                   class="tags__checkbox tags__checkbox_style_orange"
                                   {% if 'breakfast' in active_tags %}checked{% endif %}>
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="lunch" id="id_lunch"
                                   class="tags__checkbox tags__checkbox_style_green"
                                   {% if 'lunch' in active_tags %}checked{% endif %}>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="dinner" id="id_dinner"
                                   class="tags__checkbox tags__checkbox_style_purple"
                                   {% if 'dinner' in active_tags %}checked{% endif %}>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    <span class="form__error">{{ form.tags.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% if ingredients %}
                            {% for ingredient in ingredients %}
                                <div class="form__field-item-ingredient" id="ing_{{ ingredient.ingredient.id }}"><span>
										{{ ingredient.ingredient.title }} {{ ingredient.quantity }}
                                    {{ ingredient.ingredient.dimension }}</span> <span
                                        class="form__field-item-delete"></span>
                                    <input id="nameIngredient_{{ ingredient.ingredient.id }}"
                                           name="nameIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.ingredient.title }}">
                                    <input id="valueIngredient_{{ ingredient.ingredient.id }}"
                                           name="valueIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.quantity }}">
                                    <input id="unitsIngredient_{{ ingredient.ingredient.id }}"
                                           name="unitsIngredient_{{ ingredient.ingredient.id }}" type="hidden"
                                           value="{{ ingredient.ingredient.dimension }}">
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.time.id_for_label }}" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error">{{ form.time.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="image" accept='image/*' id="id_image">
                    <span class="form__error">{{ form.image.errors }}</span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">{% if recipe %} Редактирование рецепта {% else %} Создание
                    рецепта  {% endif %}</button>
                {% if recipe %}
                    <a style="margin-left: 2.5em" href="{% url 'remove_recipe' recipe.author.username recipe.id %}"
                       class="form__ingredient-link">Удалить</a>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/purchase.html
{% extends "base.html" %}
{% block title %}Список покупок{% endblock %}

{% load users_tags %}

{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for purchase in purchases %}
                <li class="shopping-list__item" data-id="{{ purchase.recipe.id }}">
                    <div class="recipe recipe_reverse">
                        {% load thumbnail %}
                        {% thumbnail purchase.recipe.image "90x90" crop="center" upscale=True as im %}
                            <img src="{{ im.url }}" alt="{{ purchase.recipe.title }}"
                                 class="recipe__image recipe__image_big">
                        {% endthumbnail %}
                        <h3 class="recipe__title">{{ purchase.recipe.title }}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ purchase.recipe.time }} мин.</p>
                    </div>
                    <a href="{% url 'remove_purchase' purchase.recipe.id %}"
                       class="shopping-list__button link">Удалить</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'get_purchase' %}">
            <button class="button button_style_blue">Скачать список</button>
        </a>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'shopList.js' %}"></script>
{% endblock %}

recipes/templates/recipes/recipe_item.html
{% load user_filters %}

<div class="card" data-id="{{ recipe.id }}">
    {% load thumbnail %}
    {% thumbnail recipe.image "364x240" crop="center" upscale=True as img %}
        <a href="{% url 'recipe' recipe.author.username recipe.id %}" class="link"><img
                src="{{ img.url }}" alt="{{ recipe.title }}" class="card__image"></a>
    {% endthumbnail %}
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe' recipe.author.username recipe.id %}"
           target="_blank">{{ recipe.title }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
                {% if "breakfast" == tag.key %}
                    <li class="card__item"><span class="badge badge_style_orange">{{ tag.value }}</span></li>
                {% endif %}

                {% if "lunch" == tag.key %}
                    <li class="card__item"><span class="badge badge_style_green">{{ tag.value }}</span></li>
                {% endif %}

                {% if "dinner" == tag.key %}
                    <li class="card__item"><span class="badge badge_style_purple">{{ tag.value }}</span></li>
                {% endif %}
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author.username %}"
                                                                     style="color: black">{{ recipe.author.get_full_name }}</a>
            </p>
        </div>

    </div>
    {% csrf_token %}
    <div class="card__footer">
        {% if not request.is_anonymous and request.user|check_purchase:recipe %}
            <button class="button button_style_light-blue-outline" name="purchases"><span
                    class="icon-check button__icon"></span> Рецепт добавлен
            </button>
        {% else %}
            <button class="button button_style_light-blue" name="purchases" data-out><span
                    class="icon-plus button__icon"></span>Добавить в покупки
            </button>
        {% endif %}

        <button class="button button_style_none"
                name="favorites"
                {% if not request.is_anonymous and request.user|check_favorites:recipe %}
                    ><span class="icon-favorite icon-favorite_active">
                {% else %}
                    data-out><span class="icon-favorite"></span>
                {% endif %}
        </span></button>
    </div>
</div>

        
  

recipes/templates/recipes/recipe_page.html
{% extends "base.html" %}

{% block title %}{{ recipe.title }}{% endblock %}

{% load user_filters %}

{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}
{% block content %}
    <div class="single-card" data-id={{ recipe.id }} data-author="{{ recipe.author.id }}">
        {% load thumbnail %}
        {% thumbnail recipe.image "480x480" crop="center" upscale=True as img %}
            <img src="{{ img.url }}" alt="{{ recipe.title }}" class="single-card__image" width="480" height="480">
        {% endthumbnail %}
        <div class="single-card__info">
            <div class="single-card__header-info">
                <h1 class="single-card__title">{{ recipe.title }}</h1>
                {% csrf_token %}
                <div class="single-card__favorite">
                    <button class="button button_style_none" name="favorites"
                            {% if not request.is_anonymous and request.user|check_favorites:recipe %}
                                ><span class="icon-favorite icon-favorite_big icon-favorite_active"></span></button>
                            {% else %}
                                data-out><span class="icon-favorite icon-favorite_big"></span></button>
                            {% endif %}
                    <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                </div>
            </div>
            <ul class="single-card__items">
                {% for tag in recipe.tags.all %}
                    {% if "breakfast" == tag.key %}
                        <li class="single-card__item"><span class="badge badge_style_orange">{{ tag.value }}</span></li>
                    {% endif %}

                    {% if "lunch" == tag.key %}
                        <li class="single-card__item"><span class="badge badge_style_green">{{ tag.value }}</span></li>
                    {% endif %}

                    {% if "dinner" == tag.key %}
                        <li class="single-card__item"><span class="badge badge_style_purple">{{ tag.value }}</span></li>
                    {% endif %}
                {% endfor %}

            </ul>
            <div class="single-card__items single-card__items_column">
                <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                <ul class="single-card__items">
                    <li class="single-card__item"><p class="single-card__text"><span
                            class="icon-user"></span> {{ recipe.author.get_full_name }} </p></li>
                    {% if not request.is_anonymous and request.user == recipe.author %}
                        <li class="single-card__item"><a style="margin-left: 2.5em"
                                                         href="{% url 'edit_recipe' recipe.author.username recipe.id %}"
                                                         class="single-card__text">Редактировать рецепт</a></li>
                    {% endif %}
                </ul>
            </div>
            <ul class="single-card__items">
                <li class="single-card__item">
                    {% if not request.is_anonymous and request.user|check_purchase:recipe %}
                        <button class="button button_style_light-blue-outline" name="purchases"><span
                                class="icon-check"></span> Рецепт добавлен
                        </button>
                    {% else %}
                        <button class="button button_style_blue" name="purchases" data-out><span
                                class="icon-plus"></span>Добавить в покупки
                        </button>
                    {% endif %}
                </li>
                <li class="single-card__item">
                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe"
                            {% if recipe.author|check_following:request.user %}
                                >Отписаться от автора
                            {% else %}
                                data-out>Подписаться на автора
                            {% endif %}
                    </button>
                </li>
            </ul>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Ингридиенты:</h3>
                <div class="single-card__items single-card__items_column">

                    {% for ingredient in ingredients %}
                        <p class=" single-card__section-item">{{ ingredient.ingredient.title }}
                            - {{ ingredient.quantity }} {{ ingredient.ingredient.dimension }}.</p>
                    {% endfor %}
                </div>
            </div>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Описание:</h3>
                <p class=" single-card__section-text">{{ recipe.description | safe }}</p>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'singlePage.js' %}"></script>
{% endblock %}

recipes/templates/recipes/subscribe_button.html
{% load user_filters %}
{% csrf_token %}
{% if user.is_authenticated %}
    <div class="author-subscribe" data-author="{{ author.id }}">
        <p style="padding: 0 0 2em 0;">
            <button class="button button_style_light-blue button_size_subscribe" name="subscribe"
                    {% if author|check_following:request.user %}
                        >Отписаться от автора
                    {% else %}
                        data-out>Подписаться на автора
                    {% endif %}
            </button>
        </p>
    </div>
{% endif %}